name: test
on:
  push:
    branches:
      - "**"

env:
  GOPRIVATE: "github.com/whywaita/*"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x
      - name: Granting private modules access
        run: |
          git config --global url."https://whywaita:${{ secrets.TOKEN }}@github.com/whywaita".insteadOf "https://github.com/whywaita"
      - name: lint
        run: |
          go get golang.org/x/lint/golint
          bin/golint -set_exit_status ./...
        env:
          GO111MODULE: off
          GOBIN: $(pwd)/bin
      - name: vet
        run: |
          go vet ./...
      - name: build
        run: go build .

  goreleaser-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x
      - name: Granting private modules access
        run: |
          git config --global url."https://whywaita:${{ secrets.TOKEN }}@github.com/whywaita".insteadOf "https://github.com/whywaita"
      - name: goreleaser check
        continue-on-error: true
        uses: goreleaser/goreleaser-action@v2
        with:
          args: check